const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR'
};

export default userTypes;
